// Code generated by protoc-gen-go.
// source: gt_base.proto
// DO NOT EDIT!

/*
Package gt_msg is a generated protocol buffer package.

It is generated from these files:
	gt_base.proto

It has these top-level messages:
	CommonError
	HHRequest
	HHResponse
	Order
	AppOrder
*/
package gt_msg

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// 0.通讯错误信息
type CommonError struct {
	Code             int32  `protobuf:"varint,1,opt,name=Code" json:"Code,omitempty"`
	SzDescribeString string `protobuf:"bytes,2,opt,name=szDescribeString" json:"szDescribeString,omitempty"`
}

func (m *CommonError) Reset()                    { *m = CommonError{} }
func (m *CommonError) String() string            { return proto.CompactTextString(m) }
func (*CommonError) ProtoMessage()               {}
func (*CommonError) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *CommonError) GetCode() int32 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *CommonError) GetSzDescribeString() string {
	if m != nil {
		return m.SzDescribeString
	}
	return ""
}

// 1.心跳请求
type HHRequest struct {
}

func (m *HHRequest) Reset()                    { *m = HHRequest{} }
func (m *HHRequest) String() string            { return proto.CompactTextString(m) }
func (*HHRequest) ProtoMessage()               {}
func (*HHRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

// 2.心跳回复
type HHResponse struct {
	ServerTimeNow int64 `protobuf:"varint,1,opt,name=serverTimeNow" json:"serverTimeNow,omitempty"`
}

func (m *HHResponse) Reset()                    { *m = HHResponse{} }
func (m *HHResponse) String() string            { return proto.CompactTextString(m) }
func (*HHResponse) ProtoMessage()               {}
func (*HHResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *HHResponse) GetServerTimeNow() int64 {
	if m != nil {
		return m.ServerTimeNow
	}
	return 0
}

// 3.订单
type Order struct {
	OrderID     string `protobuf:"bytes,1,opt,name=orderID" json:"orderID,omitempty"`
	OrderAmount string `protobuf:"bytes,2,opt,name=orderAmount" json:"orderAmount,omitempty"`
}

func (m *Order) Reset()                    { *m = Order{} }
func (m *Order) String() string            { return proto.CompactTextString(m) }
func (*Order) ProtoMessage()               {}
func (*Order) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *Order) GetOrderID() string {
	if m != nil {
		return m.OrderID
	}
	return ""
}

func (m *Order) GetOrderAmount() string {
	if m != nil {
		return m.OrderAmount
	}
	return ""
}

type AppOrder struct {
	OpenUserID string `protobuf:"bytes,1,opt,name=openUserID" json:"openUserID,omitempty"`
	ShareID    string `protobuf:"bytes,2,opt,name=shareID" json:"shareID,omitempty"`
	OrderID    string `protobuf:"bytes,3,opt,name=orderID" json:"orderID,omitempty"`
	IpAddress  string `protobuf:"bytes,4,opt,name=ipAddress" json:"ipAddress,omitempty"`
	CardPrice  string `protobuf:"bytes,5,opt,name=cardPrice" json:"cardPrice,omitempty"`
	CardGold   string `protobuf:"bytes,6,opt,name=cardGold" json:"cardGold,omitempty"`
	GameID     string `protobuf:"bytes,7,opt,name=gameID" json:"gameID,omitempty"`
	InsertID   string `protobuf:"bytes,8,opt,name=insertID" json:"insertID,omitempty"`
}

func (m *AppOrder) Reset()                    { *m = AppOrder{} }
func (m *AppOrder) String() string            { return proto.CompactTextString(m) }
func (*AppOrder) ProtoMessage()               {}
func (*AppOrder) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

func (m *AppOrder) GetOpenUserID() string {
	if m != nil {
		return m.OpenUserID
	}
	return ""
}

func (m *AppOrder) GetShareID() string {
	if m != nil {
		return m.ShareID
	}
	return ""
}

func (m *AppOrder) GetOrderID() string {
	if m != nil {
		return m.OrderID
	}
	return ""
}

func (m *AppOrder) GetIpAddress() string {
	if m != nil {
		return m.IpAddress
	}
	return ""
}

func (m *AppOrder) GetCardPrice() string {
	if m != nil {
		return m.CardPrice
	}
	return ""
}

func (m *AppOrder) GetCardGold() string {
	if m != nil {
		return m.CardGold
	}
	return ""
}

func (m *AppOrder) GetGameID() string {
	if m != nil {
		return m.GameID
	}
	return ""
}

func (m *AppOrder) GetInsertID() string {
	if m != nil {
		return m.InsertID
	}
	return ""
}

func init() {
	proto.RegisterType((*CommonError)(nil), "gt_msg.CommonError")
	proto.RegisterType((*HHRequest)(nil), "gt_msg.HHRequest")
	proto.RegisterType((*HHResponse)(nil), "gt_msg.HHResponse")
	proto.RegisterType((*Order)(nil), "gt_msg.Order")
	proto.RegisterType((*AppOrder)(nil), "gt_msg.AppOrder")
}

func init() { proto.RegisterFile("gt_base.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 300 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0x64, 0x91, 0x4f, 0x4b, 0xc3, 0x40,
	0x10, 0xc5, 0x89, 0x6d, 0xd3, 0x66, 0x4a, 0x41, 0xf6, 0x20, 0x8b, 0x88, 0x94, 0xe0, 0xa1, 0x78,
	0xf0, 0xa0, 0x9f, 0xa0, 0x34, 0x62, 0x7b, 0xf0, 0x0f, 0x51, 0xcf, 0x25, 0x6d, 0x86, 0x18, 0x30,
	0x99, 0x75, 0x66, 0xab, 0xe0, 0x47, 0xf6, 0x53, 0xc8, 0x6e, 0x9b, 0x9a, 0xe2, 0x6d, 0x7e, 0xef,
	0xed, 0xbc, 0x79, 0xb0, 0x30, 0x2a, 0xec, 0x72, 0x95, 0x09, 0x5e, 0x19, 0x26, 0x4b, 0x2a, 0x2c,
	0xec, 0xb2, 0x92, 0x22, 0xbe, 0x87, 0xe1, 0x8c, 0xaa, 0x8a, 0xea, 0x5b, 0x66, 0x62, 0xa5, 0xa0,
	0x3b, 0xa3, 0x1c, 0x75, 0x30, 0x0e, 0x26, 0xbd, 0xd4, 0xcf, 0xea, 0x12, 0x8e, 0xe5, 0x3b, 0x41,
	0x59, 0x73, 0xb9, 0xc2, 0x67, 0xcb, 0x65, 0x5d, 0xe8, 0xa3, 0x71, 0x30, 0x89, 0xd2, 0x7f, 0x7a,
	0x3c, 0x84, 0x68, 0x3e, 0x4f, 0xf1, 0x63, 0x83, 0x62, 0xe3, 0x6b, 0x00, 0x07, 0x62, 0xa8, 0x16,
	0x54, 0x17, 0x30, 0x12, 0xe4, 0x4f, 0xe4, 0x97, 0xb2, 0xc2, 0x07, 0xfa, 0xf2, 0x37, 0x3a, 0xe9,
	0xa1, 0x18, 0xcf, 0xa0, 0xf7, 0xc8, 0x39, 0xb2, 0xd2, 0xd0, 0x27, 0x37, 0x2c, 0x12, 0xff, 0x30,
	0x4a, 0x1b, 0x54, 0x63, 0x18, 0xfa, 0x71, 0x5a, 0xd1, 0xa6, 0xb6, 0xbb, 0x2a, 0x6d, 0x29, 0xfe,
	0x09, 0x60, 0x30, 0x35, 0x66, 0x1b, 0x74, 0x0e, 0x40, 0x06, 0xeb, 0x57, 0x69, 0x65, 0xb5, 0x14,
	0x77, 0x48, 0xde, 0x32, 0xc6, 0x45, 0xb2, 0x8b, 0x6a, 0xb0, 0x5d, 0xa1, 0x73, 0x58, 0xe1, 0x0c,
	0xa2, 0xd2, 0x4c, 0xf3, 0x9c, 0x51, 0x44, 0x77, 0xbd, 0xf7, 0x27, 0x38, 0x77, 0x9d, 0x71, 0xfe,
	0xc4, 0xe5, 0x1a, 0x75, 0x6f, 0xeb, 0xee, 0x05, 0x75, 0x0a, 0x03, 0x07, 0x77, 0xf4, 0x9e, 0xeb,
	0xd0, 0x9b, 0x7b, 0x56, 0x27, 0x10, 0x16, 0x59, 0xe5, 0xaa, 0xf4, 0xbd, 0xb3, 0x23, 0xb7, 0x53,
	0xd6, 0x82, 0x6c, 0x17, 0x89, 0x1e, 0x6c, 0x77, 0x1a, 0x5e, 0x85, 0xfe, 0x43, 0x6f, 0x7e, 0x03,
	0x00, 0x00, 0xff, 0xff, 0xf9, 0xd7, 0xe9, 0x5a, 0xe1, 0x01, 0x00, 0x00,
}
